### ISSUE TITLE
ERROR:  unrecognized configuration parameter "default_table_access_method"

### ISSUE THREAD

**Issue by LucaAtWork** [zonkyio/embedded-database-spring-test#82] opened 2020-02-10 11:36 UTC
Hi all,
for some reasons the "default_table_access_method" is not recognized.
I get this error:

SQL State  : 42704
Error Code : 0
Message    :  unrecognized configuration parameter "default_table_access_method"
Statement  : SET default_table_access_method = heap

If i manually remove that parameter from the sql file, it will start to work.

Is this an issue with flyway or am I doing something wrong?

Thanks

**Comment by tomix26** [comment] 2020-09-11 09:55
It would probably be better to post this question in a postgres forum. I'm closing the issue for now, feel free to reopen it if you think that the problem is related to the embedded postgres.

**Closed by tomix26** 2020-09-11 09:55 UTC
