### ISSUE TITLE
Zonky "initdb" file getting returning file not found

### ISSUE THREAD

**Issue by fx310ferreira** [zonkyio/embedded-database-spring-test#253] opened 2023-12-11 10:09 UTC
Using zonky the the database initdb script does not run it returns the following error:
`./initdb: cannot execute: required file not found`

I went to the directory, tried to run the file manually and got this error:
`bash: ./initdb: cannot execute: required file not found`

I have deleted the folder and retried several times.
What can i do to solve this?

**Comment by tomix26** [comment] 2023-12-11 13:26
There are some steps you can do:
- what versions are you using? (`embedded-database-spring-test`, `embedded-postgres`, `embedded-postgres-binaries`)
- what operating system?
- have you checked whether the `initdb` file really exists or not?

Because the problem you are facing might be related to the following issue: https://github.com/zonkyio/embedded-postgres-binaries/issues/75, which was caused by a missing library in PostgreSQL 14.10 binaries for the macOS platform.

**Comment by fx310ferreira** [comment] 2023-12-11 21:41
The file exists I think the initdb script is trying to run some file that does not exist.
I am using NixOs
```
	testImplementation "io.zonky.test:embedded-database-spring-test:2.4.0"
	testImplementation "io.zonky.test:embedded-postgres:2.0.3"
```
I don't have the binaries

**Comment by tomix26** [comment] 2023-12-18 11:28
Actually, I have no experience with NixOs, so maybe the following questions might sound a little stupid.
- Has it ever worked, or is this your first time using the library?
- Does the problem affect all versions or just this specific one?
- Are there any other clues in the log, besides the "required file not found" message?

**Comment by tomix26** [comment] 2024-01-24 10:47
I'm closing the issue, feel free to reopen it if the problem persists.

**Closed by tomix26** 2024-01-24 10:47 UTC
Labels: status: waiting-for-feedback
