### ISSUE TITLE
`Image not found` error on macOS BigSur 11.4

### ISSUE THREAD

**Issue by deepak-auto** [zonkyio/embedded-database-spring-test#168] opened 2021-06-22 20:59 UTC
After upgrading to BigSur, I faced the same problem as https://github.com/zonkyio/embedded-database-spring-test/issues/132 but moving to version `1.6.3` fixed it. After a few months, I am facing the same problem again. I suspect this is related to a (minor) macOS upgrade.

```
2021-06-22 15:58:59 [prefetching-3] INFO  i.z.t.d.p.embedded.EmbeddedPostgres - Detected a Darwin x86_64 system
2021-06-22 15:58:59 [prefetching-3] INFO  i.z.t.d.p.e.DefaultPostgresBinaryResolver - Detected distribution: 'Unknown'
2021-06-22 15:58:59 [prefetching-3] INFO  i.z.t.d.p.e.DefaultPostgresBinaryResolver - System specific postgres binaries found: postgres-darwin-x86_64.txz
2021-06-22 15:59:00 [prefetching-3] INFO  i.z.t.d.p.embedded.EmbeddedPostgres - Postgres binaries at /var/folders/41/zd97vp0x3n10bx3zczvwcyb80000gp/T/embedded-pg/PG-f3edf7fa7a0adde27d39be0b067a5997
2021-06-22 15:59:00 [initdb:pid(15733)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres - dyld: Library not loaded: @loader_path/../lib/libpq.5.dylib
2021-06-22 15:59:00 [initdb:pid(15733)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres -   Referenced from: /var/folders/41/zd97vp0x3n10bx3zczvwcyb80000gp/T/embedded-pg/PG-f3edf7fa7a0adde27d39be0b067a5997/bin/initdb
2021-06-22 15:59:00 [initdb:pid(15733)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres -   Reason: image not found
2021-06-22 15:59:00 [initdb:pid(15734)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres - dyld: Library not loaded: @loader_path/../lib/libpq.5.dylib
2021-06-22 15:59:00 [initdb:pid(15734)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres -   Referenced from: /var/folders/41/zd97vp0x3n10bx3zczvwcyb80000gp/T/embedded-pg/PG-f3edf7fa7a0adde27d39be0b067a5997/bin/initdb
2021-06-22 15:59:00 [initdb:pid(15734)] INFO  i.z.t.d.p.embedded.EmbeddedPostgres -   Reason: image not found
2021-06-22 15:59:00 [main] ERROR i.z.t.d.p.FlywayEmbeddedPostgresDataSourceFactoryBean - Unexpected error during the initialization of embedded database
```

Versions:
embedded-database-spring-test 1.6.3
macOS BigSur 11.4
Java version: 1.8

**Comment by deepak-auto** [comment] 2021-06-22 21:29
Update:

The problem went away when I moved to `embedded-database-spring-test:2.0.1` and followed the steps mentioned in https://github.com/zonkyio/embedded-database-spring-test#using-zonky-provider-previous-default. Is this the recommended solution or will a patch fix be back-ported to version 1.6.x?

**Comment by tomix26** [comment] 2021-06-26 14:45
@deepak-auto Are you sure you were using version `1.6.3`? Because this version depends on `io.zonky.test.postgres:embedded-postgres-binaries-xxx:10.15.0-1` binaries, which are the same ones used in version `2.0.1`. Could you please test what happens when you use version `2.0.0`? Do you get the same result or is there a difference?

**Comment by deepak-auto** [comment] 2021-07-12 20:06
Hi, sorry for the late reply. Yes, the version I used is `1.6.3`. For the version `2.0.1`, I followed the instructions under https://github.com/zonkyio/embedded-database-spring-test#using-zonky-provider-previous-default and used set the version of `embedded-postgres-binaries-bom` to `13.2.0`.

**Comment by tomix26** [comment] 2021-07-18 16:29
Since the reported error is closely related to the version of the binaries being used, I think this issue is irrelevant. You can simply use `io.zonky.test.postgres:embedded-postgres-binaries-xxx:13.2.0` binaries together with any older version of the `embedded-database-spring-test` library and that should solve the error. So I'm closing the issue for now, but feel free to reopen it if you can provide some additional information to reproduce the problem.

**Closed by tomix26** 2021-07-18 16:29 UTC
Labels: status: waiting-for-feedback
